steps:
  # 1. Build the Docker image
  # FIXED: Updated the repository name to 'service-status-repo' to match subsequent steps
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '--no-cache'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/service-status-repo/$PROJECT_ID:$COMMIT_SHA'
      - '.'
      - '-f'
      - 'Dockerfile'

  # 2. Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/service-status-repo/$PROJECT_ID:$COMMIT_SHA'

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: Deploy
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'services'
      - 'update'
      - 'pt-service-status'
      - '--platform=managed'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/service-status-repo/$PROJECT_ID:$COMMIT_SHA'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--quiet'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/service-status-repo/$PROJECT_ID:$COMMIT_SHA'

options:
  substitutionOption: 'ALLOW_LOOSE'
  logging: 'CLOUD_LOGGING_ONLY'

tags:
  - 'gcp-cloud-build-deploy-cloud-run'
  - 'gcp-cloud-build-deploy-cloud-run-managed'